### ISSUE TITLE
[Feat] 변경된 마이페이지 UI 반영 ( 1릴 )

### ISSUE THREAD

**Issue by seongmin221** [GEON-PPANG/GEON-PPANG-iOS#132]
## 💡 Issue

변경된 마이페이지 UI 구현하기 위한 이슈입니닷

## 📝  Todo
- [ ] 이용약관, 문의하기 추가
- [ ] 로그아웃, 회원탈퇴 추가
- [ ] 로그아웃, 회원탈퇴 시 Alert 창 띄우기
