### ISSUE TITLE
[Fix] 디자인 이슈 수정

### ISSUE THREAD

**Issue by jeongdung-eo** [GEON-PPANG/GEON-PPANG-iOS#173]
## 💡 Issue
- 자잘한 디자인 이슈 수정을 위한 이슈입니다.
## 📝  Todo
- [x] 홈 바텀 셀 글자 잘리는 이슈
- [x] 빵집 리스트 북마크 레이아웃 이슈 
- [x] 리스트 셀 지역 font, 이미지 size
- [x] 빵집 리스트 sort view background color
- [x] 빵집 리스트 sort view checkbox tint color
- [x] signIn login 텍스트필드  padding 
- [x] 로그인 비밀번호 security 버튼 안나타나는 이슈
