### ISSUE TITLE
[Setting] 앰플리튜드 세팅 

### ISSUE THREAD

**Issue by jeongdung-eo** [GEON-PPANG/GEON-PPANG-iOS#178]
## 💡 Issue
- 앰플리튜드 세팅을 위한 이슈입니다
## 📝  Todo
- [ ] 앰플리튜드 sdk 설치
- [ ] 앰플리튜드 api key 세팅 
- [ ] event심기 위한 기초 세팅
