### ISSUE TITLE
[Feat] 상세페이지 바텀시트 버튼들 바뀐 디자인 적용 및 로직 수정

### ISSUE THREAD

**Issue by ckkim817** [GEON-PPANG/GEON-PPANG-iOS#181]
## 💡 Issue

상세페이지 바텀시트 버튼 디자인 수정을 위한 이슈입니다.
+북마크 숫자도 바로바로 뷰에 반영되게 하려구요 ~

## 📝  Todo
- [ ] 즐겨찾기 버튼 디자인 수정
- [ ] 리뷰 작성하기 버튼 디자인 수정
- [ ] 상세페이지에서 북마크 숫자 바로바로 뷰에 반영되게 로직 수정
