### ISSUE TITLE
[Fix] 추가로 발생한 버그와 놓친 부분 해결

### ISSUE THREAD

**Issue by seongmin221** [GEON-PPANG/GEON-PPANG-iOS#191]
## 💡 Issue

그 새 버그가 또 발생해서 ... 해결하기 위한 이슈입니닷 ...
UI 놓친 부분들도 있더라구요 ...
꼼꼼히 하지 못해 죄송합니다 ㅠ

## 📝  Todo
- [x] 마이페이지 타이틀 UI 조정
- [x] 리뷰 페이지 GMO 등 있는 태그들 조정
- [x] 마이페이지 필터 칩 레이아웃 조정
- [x] 마이페이지 필터 없으면 말풍선 띄우기
