### ISSUE TITLE
[Feat] 디자인 시스템 CTA 버튼 구현

### ISSUE THREAD

**Issue by seongmin221** [GEON-PPANG/GEON-PPANG-iOS#270]
## 💡 Issue

디자인 시스템에 CTA 버튼을 구현하기 위한 이슈입니다

## 📝  Todo
- [ ] 색별로 설정할 수 있게 구현
- [ ] 버튼 액션 추가할 수 있도록
- [ ] 내부 텍스트 입력할 수 있도록
