### ISSUE TITLE
[Feat] 홈 컬렉션뷰 구현

### ISSUE THREAD

**Issue by jeongdung-eo** [GEON-PPANG/GEON-PPANG-iOS#29]
## 💡 Issue
- 홈 컬렉션뷰 구현을 위한 이슈입니다.
## 📝  Todo
- [ ]  컬렉션뷰
    - [ ]  Section1, Section2 컬렉션뷰 헤더
    - [ ]  Section1 cell
        - [ ]  셀을 누르면 상세보기로 화면 전환
        - [ ]  스크랩 버튼 누르면 버튼 색상 변경 및 서버 통신
    - [ ]  Section2
        - [ ]  cell셀을 누르면 상세보기로 화면 전환
        - [ ]  스크랩 버튼 누르면 버튼 색상 변경 및 서버 통신
    - [ ]  Section2 컬렉션뷰 푸터 - UILabel
    - [ ]  Section2 컬렉션뷰 - supplementary view로 백그라운드 컬러 회색으로 넣기
