### ISSUE TITLE
[Feat] WriteReviewViewController 기능 구현

### ISSUE THREAD

**Issue by seongmin221** [GEON-PPANG/GEON-PPANG-iOS#31]
## 💡 Issue

#16 에서 UI 먼저 구현하였고, 이제 분기처리를 위한 이슈 입니다 !

## 📝  Todo
- [ ]  ‘건빵집은 어떠셨나요?’ 선택
    - [ ]  좋아요 선택 시 ‘어떤것을 추천하나요?’ 활성화
    - [ ]  별로에요 선택 시 ‘어떤것을 추천하나요?’ 비활성화
- [ ]  ‘좋아요’ - ‘어떤것을 추천하나요?’ 선택
    - [ ]  복수 선택 가능
    - [ ]  선택 시 UI 변경
    - [ ]  적어도 하나 선택 시 텍스트필드 활성화
- [ ]  ‘좋아요’ - ‘어떤것을 추천하나요?’ - 텍스트필드 작성
    - [ ]  10자 이상이면 작성하기 버튼 활성화
    - [ ]  1 ~ 9자일 때 빨간색 테두리로
- [ ]  ‘별로에요’ - 텍스트필드 작성
    - [ ]  10자 이상이면 작성하기 버튼 활성화
    - [ ]  1 ~ 9자일 때 빨간색 테두리로
