### ISSUE TITLE
[Feat] 필터 선택 뷰 구현

### ISSUE THREAD

**Issue by seongmin221** [GEON-PPANG/GEON-PPANG-iOS#39]
## 💡 Issue

필터 선택하는 뷰 구현에 대한 이슈 입니닷

## 📝  Todo
- [ ] 필터 선택 collection view cell 통일
- [ ] view 별로 중복선택, 단일선택 구현
- [ ] 데이터 관리 주의
