### ISSUE TITLE
[Feat] 마이페이지 뷰 구현

### ISSUE THREAD

**Issue by seongmin221** [GEON-PPANG/GEON-PPANG-iOS#51]
## 💡 Issue

마이페이지 뷰 구현하기 위한 이슈 입니닷

## 📝  Todo
- [ ] 전체 CollectionView 로 구현
  - [ ] 상단 뷰 header 로 구현
  - [ ] Section 2개 구현
  - [ ] 하단 뷰 footer 로 구현
