### ISSUE TITLE
[Feat] 디테일 뷰에서 사용할 바텀 버튼 뷰와 API 구현

### ISSUE THREAD

**Issue by seongmin221** [GEON-PPANG/GEON-PPANG-iOS#85]
## 💡 Issue

<img width="482" alt="image" src="https://github.com/GEON-PPANG/GEON-PPANG-iOS/assets/72431640/2a965d6c-9dfa-4587-ab74-8ebe89642dbc">

## 📝  Todo
- [ ] 버튼 UI 구현
- [ ] 버튼 API 구현
- [ ] 리뷰 작성 VC 연결
