### ISSUE TITLE
[Feat] 디테일뷰로 화면 전환 연결

### ISSUE THREAD

**Issue by jeongdung-eo** [GEON-PPANG/GEON-PPANG-iOS#92]
## 💡 Issue
- 화면 전환 연결하는 이슈입니다.
## 📝  Todo
- [ ] 홈 베스트 빵집에서 디테일뷰 화면 전환 연결 
- [ ] 홈 베스트 리뷰에서 디테일뷰 화면 전환 연결 
- [ ] 검색뷰에서 디테일뷰 화면 전환 연결 
- [ ] 빵집 리스트에서 디테일뷰 화면 전환 연결 
- [ ] 저장목록에서 디테일뷰 화면 전환 연결
